### ISSUE TITLE
Migrate build to Stack

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/codingteam.org.ru#31]
Stack is more convenient way of managing the Haskell environment. Let's stick to it.

**Comment by rexim** [comment]
:goat:

**Comment by ForNeVeR** [comment]
Or maybe enable Nix support for that matter. We can also do both.

**Comment by rexim** [comment]
:goat: x2

**Comment by ForNeVeR** [comment]
Superseded by #34.
