### ISSUE TITLE
Rewrite in more easily deployable technological stack

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/codingteam.org.ru#34]
## Conclusion

Now evaluating **vibe.d**.

## Original post

Well, I am upset a bit, so please consider my words tolerable.

I want to rewrite that. I don't like neither current implementation or its build process or its setup on our production server. Also our six months are already over, so we need to try something new (and, surely, better) >,3

I want our next site implementation to be easily manageable (so I don't need to run the whole virtual fawking machine just for the compilation purpose). I'd formulate the requirements as the following (sorted by priority):

1. The technological stack should be cross-platform (i.e. we should be able to develop it on either Linux or Windows without too much fuss).
2. It should be supported by a strongly typed language on both server- and client-side _if we want any code to run on client_ (sorry, Catberry, but not _yet_).
3. We need easy crossoperation with things like https://github.com/codingteam/Gestalt and https://github.com/ForNeVeR/EvilPlanner.
4. The technological stack should support cross-platform build _(because our build server works on Windows and I don't want to change that; our production server works on Ubuntu and we don't want to change that)_. Note that Haskell have some problems with that :(
5. We better should have a specialist willing to support that stack and _feeling enthusiastic_ about that (I am really sorry, but it turned out that I'm not such a specialist for Haskell/cabal/yesod/whatever-based stack, especially in cross-build scenarious; see #32 for details).
6. Ideally, that specialist should be one of the guys who already have root access to ctor server (that's not _that_ important, but that means that voices from me or @rexim or @hagane should be considered with much attention).
7. Even more ideally this specialist should be _me_ because I have both time and a necessary bit of enthusiasm while working for the good of our little _but fkin great_ community.

Every single one of these requirements could be discussed.

Based on my personal knowledge and analysis of these requirements, I think that we could use F# and .NET Core. It's still in RC (not released), but I personally see no problems with that and I'm personally ready to overcome any problems that could dare to stay in our way.

@Minoru, @hagane, @rexim, @gsomix, @Newlifer, @ttldtor, I invite you guys to discussion. Maybe we should choose something less exotic? What other options I've forget? Maybe Scala? Maybe something else?

That site is our HQ, this is out fawking face. We should make it ideal _at least in some points of view_.

**Comment by Newlifer** [comment]
I suggest [vibe.d](http://vibed.org/). It's crossplatform, usefull, featurefull.

**Comment by ForNeVeR** [comment]
Could I build the binary on Windows and execute on Linux?

**Comment by Newlifer** [comment]
Theoretically there shouldn't be a problem for GDC or LDC (D frontend 
with LLVM backend) to do cross compilation.

**Comment by ForNeVeR** [comment]
@Newlifer, @ttldtor you seem to be a bit more informed about D than me. Is there sort of "production"-ready solution for Windows -> Linux cross-compiling? I've googled that, but still haven't succeed. That would grant D some additional points if it supports that sort of cross-compilation.

**Comment by Minoru** [comment]
From what I see, codingteam.org.ru is just a bunch of static pages. 
They're almost never updated, so the simplest approach would be to write 
the whole thing by hand. In HTML. No, I'm not insane, where are you 
dragging me—

I'd like to see if anyone has any plans for CTOR. It will be easier to 
decide on a stack if we know, roughly at least, what we're going to 
build.

I, for one, want to list top projects as served by Gestalt. This can be 
facilitated with a bit of simple client-side JS (just a couple of HTTP 
requests and DOM modifications, really.)

**Comment by ForNeVeR** [comment]
Yes I have the plans for it. Yes, the most obvious is the project list (that could be implemented in JS that could connect to some another subdomain/server). But we could also use the dynamically updatable room logs (as implemented in [Yog-Sothoth](https://github.com/ForNeVeR/yog-sothoth)), some blog agregator etc.

About Gestalt - I thought that our HQ site would be frontend for that, and would proxy/cache/whatever any queries. So Gestalt API would be private to their intercommunication and not necessarily accessible from outside.

**Comment by rexim** [comment]
@ForNeVeR do we actually need a backend to integrate with EvilPlanner and Gestalt? If not, pure client side application on TypeScript seems pretty reasonable for me.

**Comment by Minoru** [comment]
>But we could also use the dynamically updatable room logs (as 
>implemented in [Yog-Sothoth](https://github.com/ForNeVeR/yog-sothoth)), 
>some blog agregator etc.

Any good reason to bundle it all up into one service? I'd rather see 
a simple webpage pointing to different things—here's a page with logs, 
here's out blog planet etc.

As for Gestalt, I didn't make any assumptions about who the clients are, 
so there's no problem using it however you want. In the example above 
I just made it as simple as possible, but you sure can hide Gestalt 
behind another service.

**Comment by ForNeVeR** [comment]
@rexim,

> do we actually need a backend to integrate with EvilPlanner and Gestalt?

I guess... not. But that's a bit complicated, see below.

@Minoru,

> Any good reason to bundle it all up into one service?

I think that the main reason is that I wanted one single point (_of failure, löl_) to manage all of our public accessible API. Maybe that's too much; maybe it would complicate things more than it should.

I see and approve your point about Gestalt, but its usage directly from browser could create some small (_solvable_) difficulties for browser applications regarding [CORS](https://ru.wikipedia.org/wiki/Cross-origin_resource_sharing).

@rexim, @codingteam/owners:

I think that the point about TypeScript (well, maybe not TypeScript, but Elm or PureScript - whatever) is viable. We could easily deploy that with some HTML shits, it's crossplatform etc. etc.

But that creates some problems for the site users who have chosen to disable JavaScript in their browsers. We _already_ have some dynamic content on our site (and that's our log page that tries to pick the proper today's link for DeadBot logs), and currently it works without JS at all. So, guys, you'll have to help me to pick the decision here:

- should we ignore those sick fockers who visit our site with JavaScript disabled in their browsers,
- or do these respectable gentlemen represent a significant part of our site auditory, and we want to fully support them?

**Comment by rexim** [comment]
I vote for the second option (support people with disabled JavaScript). And I like the idea of using F# on the backend.

**Comment by Newlifer** [comment]
Well, F# would be nice as well.

**Comment by hagane** [comment]
I'm not sold on F# for backend. It kinda fails in cross-platform stack department and totally fails cross-platform development and easiness-of-management.

Seeing as @codingteam is focused on learning new stuff (at least for me), I'm with @Newlifer on this one. Let's try D, because a). why not? and b). because we can.

Yet we really should decide on a direction and a vision for the future of CTOR.

**Comment by ForNeVeR** [comment]
From the discussion with @ttldtor I've learned that there's still no hope for easy crosscompilation for D. But it's still an option.

> It kinda fails in cross-platform stack department and totally fails cross-platform development and easiness-of-management.

Sorry, I cannot understand what are you talking about. As far as I can see, `dotnet new` [supports](https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki#how-to-start-with-net-cli) `--lang f#` option and should do everything properly.

**Comment by ForNeVeR** [comment]
So currently I'd object your argument about maintainability and cross-platformery at least until I'll be able to test it myself. After that maybe I'll declare F# as bad option, and turn to other ideas.

**Comment by ForNeVeR** [comment]
And still nobody talking about Scala. But why? :confused:

**Comment by hagane** [comment]
As I said before, Codingteam is primarily a vessel of learning to me, a think-tank if you will. We already can do Scala. So let us try something new, I say.

**Comment by ForNeVeR** [comment]
That argument wasn't discarded and I agree with it. Any other ideas? I think vide.d will get to 2nd round.

**Comment by ForNeVeR** [comment]
Well, according to my schedule, it's time to summarize all the arguments and take next actions.

Even I cannot ignore the community so much, so if you guys saying that we should give vibe.d a try - so be it. I'll begin evaluation of vibe.d stack and we'll see how it will work for us.

**Comment by hagane** [comment]
@ForNeVeR please ping back with your findings, especially if you discover some issues with D web stack and/or its' compatibility with production environment.

Meanwhile, I feel we need to discuss something else.

**Comment by ForNeVeR** [comment]
Yes, I will surely post the status report.

**Comment by hagane** [comment]
@ForNeVeR FYI, I've made an independent inquiry into the vibe.d stack. D itself looks okay and tooling is more than adequate, but there are some issues nevertheless.

1. vibe.d is rough and raw, and there's a lot of boilerplate and plumbing code needed;
1. Cross-compilation is *kinda* there, if you're willing to play with various implementations and backends;
1. I'd loathe to expose a native web app straight to the 'net, especially because vibe.d itself is not confirmed as a stable and secure framework. That, of course can be mitigated by proxying it with nginx or something.

**Comment by ForNeVeR** [comment]
We're already proxying all our stuff through nginx, that's not a problem. And, yeah, regarding crosscompilation - I'm ready to compile code back on Virtualbox, given build reproducibility.
