### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Minoru** [codingteam/codingteam.org.ru#72]
When connecting to https://codingteam.org.ru, I now get an error:

> codingteam.org.ru uses an invalid security certificate.
>
> The certificate expired on 19 May 2019, 18:09. The current time is 20 May 2019, 18:50.
>
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by ForNeVeR** [comment]
Thanks, fixed.

For now, we still have manual certificate update process, because I had no time to set up the automatic one :(

The issue is listed as https://github.com/codingteam/devops/issues/29.
